### ISSUE TITLE
Dependencies for ubuntu trusty

### ISSUE THREAD

**Issue by sigmonsays** [mrzool/letter-boilerplate#3]
What are the dependencies for working with ubuntu trusty?

I installed texlive-xetex and pandoc but when I run make I receive the folloowing

<pre>
$ make
pandoc details.yml letter.md -o output.pdf --latex-engine=xelatex --template=template.tex
pandoc: Error producing PDF from TeX source.
! LaTeX Error: File `fontspec.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 
! Emergency stop.
<read *> 

l.6 ^^M

make: **\* [output.pdf] Error 43
<pre>

**Comment by sigmonsays** [comment]
I used apt-file to determine I was also missing texlive-latex-recommended and texlive-latex-extra

after 558MB packages installed (not even including the others), i'm not sure this is a light weight tool.

**Comment by sigmonsays** [comment]
After all this the build still dies with a missing font.

<pre>
$ make
pandoc details.yml letter.md -o output.pdf --latex-engine=xelatex --template=template.tex
pandoc: Error producing PDF from TeX source.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
! fontspec error: "font-not-found"
! 
! The font "Hoefler Text" cannot be found.
! 
! See the fontspec documentation for further information.
! 
! For immediate help type H <return>.
!...............................................  
                                                  
l.36 ...Common}, Numbers={OldStyle}]{Hoefler Text}
make: *** [output.pdf] Error 43
</pre>

**Comment by mrzool** [comment]
As the saying goes, when all else fails, read the fine manual!

One thing at a time:
- `fontspec` is listed among the required packages in the [dependencies](https://github.com/mrzool/letter-boilerplate#dependencies) section of the `README`. You might want to run `tlmgr install fontspec` and do the same for all the listed packages. You can of course install the whole list with a single `tlmgr install` command.
- I'm aware that a full TeX installation is pretty heavy. That's why, in the `README`, I recommend installing the smaller version `texlive-base` and adding only the required packages with `tlmgr` afterwards (see point above) instead of installing the full version, which includes tons of extra packages that you will probably never need.
- You don't have [Hoefler Text](http://www.typography.com/fonts/hoefler-text/overview/) installed on your system. Change the `mainfont` option in `details.yml` to a font that you have available. The utility [`fc-list`](http://manpages.ubuntu.com/manpages/hardy/man1/fc-list.1.html) can be used to list all your available fonts. [`font-manager`](https://code.google.com/p/font-manager/) provides a GUI for Linux similar to the one of Font Book on OS X. [My article](http://mrzool.cc/writing/typesetting-automation/) contains instructions on how to deal with the settings.
