### ISSUE TITLE
Subject line ignores lang setting

### ISSUE THREAD

**Issue by Kraymer** [mrzool/letter-boilerplate#5]
The word "Subject" is hard-coded in the template thus _ruining_ a letter compiled with `lang != english`

**Comment by mrzool** [comment]
Yes, that label is hard coded in the template. I don't know how I could bind it to `lang` other than by writing a huge `if` statement that includes a translated label for each possible language, so that's clearly not a viable solution. I'm also not aware of a way of translating it automatically through `polyglossia`, so right now the only way to achieve what you want is by manually editing the template. I have the same issue on a larger scale in [invoice-boilerplate](https://github.com/mrzool/invoice-boilerplate), where the strings to translate manually are several, and I recommend to do so in the readme.

I might consider to get rid of it entirely to make things easier. If someone has a better solution to deal with this, suggestions and pull requests are welcome.

**Comment by mrzool** [comment]
After some thought I've decided to get rid of the _Subject_ label entirely, since it causes more problems than it solves. It can easily be added to the template by hand if that's deemed necessary.
